name: Update Docker Hub README

on:
  push:
    branches:
      - main
    paths:
      - README.md
  workflow_dispatch:

jobs:
  push-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Push README to Docker Hub
        uses: christian-korneck/docker-pushrm-action@v1.9.0
        with:
          provider: dockerhub
          dockerhub_user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_pass: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: provokingchaos/waterguru2mqtt
          readme_file: "README.md"
